version: '0.1'
services:
  mysql:
    container_name: indicator-mysql
    image: mysql
    ports:
      - 5006:3306
    environment:
      - MYSQL_ROOT_PASSWORD=jzyismylover
  redis:
    container_name: indicator-redis
    image: redis
    ports:
      - 6379:6379
    command:
      --requirepass "jzy"