version: '3'
services:
  ocr:
    image: 172.16.234.200/server_app/indicator-backend-ocr:latest
    ports:
      - 25001:5000
  redis:
    container_name: indicator-reids
    image: redis:alpine
    ports:
      - 25639:6379
    command:
      --requirepass "jzy"
  mysql:
    container_name: indicator-mysql
    image: mysql
    ports:
      - 25006:3306
    environment:
      MYSQL_ROOT_PASSWORD: jzyismylover
      MYSQL_DATABASE: indicator