version: '3'

services:
  ocr:
    container_name: flask
    build: .
    ports:
      - 3500:5000
    links:
      - redis
    volumes:
      - /usr/local/share/nltk_data:/root/nltk_data
  redis:
    container_name: redis
    image: redis:alpine