version: '3'
services:
  ocr:
    image: 172.16.234.200/server_app/indicator-backend-ocr:latest
    ports:
      - 25001:5000
    environment:
      - MYSQL_HOSTNAME=172.16.234.200
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=indicator
      - MYSQL_PASSWORD=MYSQL_indicator
      - MYSQL_DBNAME=indicator
  redis:
    image: redis:alpine
    command:
      --requirepass "jzy"
  web:
    image: 172.16.234.200/server_app/indicator-extraction-tool
    ports:
      - 25002:80