from utils.useForFactory import BaseUtils
from utils.useForEnglishInstance import ENUtils
from utils.useForChineseInstance import ZHUtils
from utils.useForJapanInstance import JAUtils
from utils.useForIndonesiaFactory import IDUtils
from utils.useForTagaloInstance import TAUtils
from utils.useForThailandInstance import THUtils
from utils.useForBumeseInstance import BUUtils
from utils.useForLaosInstance import LAOUtils
from utils.useForKampucheanInstance import KAMUtils
from utils.useForVietnameseInstance import VietnaUtils
from utils.useForBengalInstance import BengaliUtils
from utils.useForKoreanInstance import KoreanUtils
from utils.useForTurkishInstance import Turkishutils
from utils.useForSpanishInstance import SpanishUtils
from utils.useForPortugueseInstance import PortugueseUtils
from utils.useForPersiannstance import PersianUtils
from utils.useForArabicInstance import ArabyUtils

